
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexsyn;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int REALN = 16;
  public static final int LT = 18;
  public static final int ELSE = 14;
  public static final int PLUS = 22;
  public static final int RPAREN = 6;
  public static final int CHART = 8;
  public static final int SEMI = 4;
  public static final int WHILE = 12;
  public static final int BOOLT = 9;
  public static final int IF = 13;
  public static final int RCBRACK = 3;
  public static final int FLOATT = 10;
  public static final int GT = 20;
  public static final int LPAREN = 5;
  public static final int LE = 19;
  public static final int ID = 17;
  public static final int EOF = 0;
  public static final int DIV = 25;
  public static final int MINUS = 23;
  public static final int GE = 21;
  public static final int error = 1;
  public static final int LCBRACK = 2;
  public static final int ASSIGN = 11;
  public static final int INTT = 7;
  public static final int MUL = 24;
  public static final int INTN = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LCBRACK",
  "RCBRACK",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "INTT",
  "CHART",
  "BOOLT",
  "FLOATT",
  "ASSIGN",
  "WHILE",
  "IF",
  "ELSE",
  "INTN",
  "REALN",
  "ID",
  "LT",
  "LE",
  "GT",
  "GE",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV"
  };
}

