all: tp2
	
tp2:
	javac lexer/*.java
	javac symbols/*.java
	javac inter/*.java
	javac parser/*.java
	javac main/*.java

.PHONY: clean
clean:
	rm -rf lexer/*.class
	rm -rf symbols/*.class
	rm -rf inter/*.class
	rm -rf parser/*.class
	rm -rf main/*.class
